### ISSUE TITLE
is there an upgrade path for older than 6.7LTS?

### ISSUE THREAD

**Issue by DemianTinkiel** [SonarSource/mysql-migrator#43]
I have 5.4

**Comment by zeyangli** [comment]
Hello, this tool is no problem, it works well. Our current platform is 6.7.7 LTS, I suggest you upgrade 5 to 6, then 6 to 7. I just completed the upgrade experiment yesterday. Please refer to my article. https://github.com/zeyangli/SonarQube-docs/blob/master/05-SonarQube%E6%A8%A1%E6%8B%9F%E5%8D%87%E7%BA%A7.md

**Comment by DemianTinkiel** [comment]
Thanks for that @zeyangli. I decided to do a fresh install since historical data is not that important and every project gets created on execution in jenkins anyway
